package Record;

import Payment.Payment;
import Product.Product;
import Product.MovieTicket;
import selectMovieModule.Customer;

import java.util.ArrayList;
import java.util.List;


/**
 * PaymentRecord class that contains the payment record of a customer<br>
 * The payment record contains the customer, products, movie tickets and payment details<br>
 * The payment record is stored in a list of all payment records<br>
 * The payment record is created when a customer makes a payment<br>
 * The payment record is stored in record class, so that they cannot be modified once created<br>
 *<br><br> <strong>Note: the getters are generated by java, to use them, simply call the methods by its corresponding variable name 
 * e,g to get the customer info, you can use customer()</strong> 
 */
public record PaymentRecord(Customer customer, List<Product>productList, List<MovieTicket> movieTicketList, Payment payment) {
    // TODO: save the record to database
    private static final List<PaymentRecord> allRecord = new ArrayList<>();

    /**
     * Constructor for PaymentRecord class
     * @param customer : customer that made the payment
     * @param productList : list of products bought
     * @param movieTicketList : list of movie tickets bought
     * @param payment : payment details
     */
    public PaymentRecord(Customer customer, List<Product> productList, List<MovieTicket> movieTicketList, Payment payment) {
        this.customer = customer;
        this.productList = productList;
        this.movieTicketList = movieTicketList;
        this.payment = payment;
        allRecord.add(this);
    }
    
    /**
     * Get all payment records
     * @return list of all payment records
     */
    public static List<PaymentRecord> getAllRecord() {
        return allRecord;
    }
} 
