package Record;

import Payment.Payment;
import Product.Product;
import selectMovieModule.Customer;
import selectMovieModule.Movie;

import java.util.ArrayList;
import java.util.List;


/**
 * PaymentRecord class that contains the payment record of a customer
 * The payment record contains the customer, products, movies and payment details
 * The payment record is stored in a list of all payment records
 * The payment record is created when a customer makes a payment
 * The payment record is stored in record class, so that they cannot be modified once created
 *<br><br> <strong>Note: the getters are generated by java, to use them, simply call the methods by its corresponding variable name 
 * e,g to get the customer info, you can use customer()</strong> 
 */
public record PaymentRecord(Customer customer, List<Product>productList, List<Movie>movieList, Payment payment) {
    private static List<PaymentRecord> allRecord = new ArrayList<>();

    public PaymentRecord(Customer customer, List<Product> productList, List<Movie> movieList, Payment payment) {
        this.customer = customer;
        this.productList = productList;
        this.movieList = movieList;
        this.payment = payment;
        allRecord.add(this);
    }
    
    public static List<PaymentRecord> getAllRecord() {
        return allRecord;
    }
} 
